import type { ThemeDefinition } from './types'

/**
 * Base swatches from your palette (hex lowercase for CSS).
 * Variants below permute which swatch fills each UI role.
 */
export const pearTomatoPalette = {
  crema: '#f2e7cb',
  pear: '#eebf43',
  tomato: '#c54f2d',
  mint: '#94b38a',
  darkSage: '#2f3828',
  darkSageMuted: '#4a5642',
  darkTomato: '#4a2618',
  darkTomatoMuted: '#6b3a28',
  darkMint: '#2a3528',
  darkMintMuted: '#3d4d3a',
  textMutedWarm: '#6d6658',
  textMutedCool: '#5a6356',
  chromeDeeperCrema: '#e5d9c0',
  chromePearTint: '#ebe0c8',
  chromeMintTint: '#dce8d6',
  chromeSageFrame: '#d4decf',
  midGold: '#d9a24a',
  midTomatoPear: '#d97a50',
  midMintPear: '#a8c59e',
  midCrema: '#efe4d4',
} as const

const PEAR_TOMATO_REF = '/theme-refs/botanical-palette.png'
const BISTRO_REF = '/theme-refs/bistro-palette.png'

/**
 * Hot Paprika, Honeycomb, Biscuit, Crumpet — bistro / café palette.
 */
export const bistroPalette = {
  paprika: '#b53324',
  honeycomb: '#e5a657',
  biscuit: '#dfbc94',
  crumpet: '#f5e2ce',
  darkPaprika: '#5a2218',
  darkPaprikaMuted: '#7a3d32',
  darkWarmBrown: '#4a3528',
  darkWarmBrownMuted: '#6b4f42',
  textMuted: '#7a6558',
  midHoneyPaprika: '#c99140',
  chromeBiscuit: '#e8d2b8',
  chromeDeeper: '#dbc4a8',
  creamBiscuitWash: '#f2e4d4',
} as const

const SUNSHINE_REF = '/theme-refs/sunshine-palette.png'

/**
 * Sunshine, Cream, Crisp Carrot, Tomato Burst, Forest Green, Kiwi — high-contrast fresh palette.
 */
export const sunshinePalette = {
  sunshine: '#ffc926',
  cream: '#f3e8cc',
  carrot: '#f96015',
  tomato: '#d52518',
  forest: '#18542a',
  kiwi: '#9abc05',
  forestMuted: '#2a6b40',
  darkTomatoInk: '#5c1810',
  darkTomatoInkMuted: '#7a2e22',
  textMuted: '#5a5348',
  midSunshineCarrot: '#fcb01e',
  midCarrotTomato: '#ea4216',
  chromeCream: '#e8dcc4',
  chromeKiwiTint: '#dde6c8',
  creamSunshineWash: '#faf4e0',
} as const

const HONEY_REF = '/theme-refs/honey-palette.png'

/**
 * 蜜色の詩 — Bitter Cocoa, Burnt Red, Honey Gold, Muted Tan, Sunlit Honey.
 */
export const honeyPalette = {
  cocoa: '#372111',
  burnt: '#7e170d',
  gold: '#b97621',
  tan: '#ce9c6c',
  sunlit: '#ebce79',
  cocoaMuted: '#4d3220',
  cocoaMuted2: '#5c4334',
  textMuted: '#6b5a48',
  midGoldSunlit: '#d7a84d',
  midBurntGold: '#9c4717',
  creamSoft: '#f5ead4',
  creamSunlitWash: '#fdf4d4',
  chromeTan: '#e2c9a8',
  chromeDeep: '#c4a882',
} as const

const MARMALADE_REF = '/theme-refs/marmalade-palette.png'

/**
 * Toast & marmalade — Deep Caramel, Tangy Orange, Burnt Orange, Caramel Milk, Honey Milk.
 */
export const marmaladePalette = {
  deepCaramel: '#734933',
  tangy: '#fd5a01',
  burnt: '#ce5c03',
  caramelMilk: '#d19975',
  honeyMilk: '#ffe6c1',
  caramelMuted: '#8a6048',
  textMuted: '#7a6558',
  midTangyBurnt: '#e85b02',
  midHoneyCaramel: '#e8bfa3',
  chromeCaramel: '#e8c4a8',
  chromeDeep: '#d4aa8a',
  creamWash: '#fff8ec',
} as const

const JEWEL_REF = '/theme-refs/jewel-palette.png'

/**
 * 午後3時の宝石 — Berry Wine, Cherry Glow, Golden Mustard, Cream Sand, Vanilla Mist.
 */
export const jewelPalette = {
  berryWine: '#6c1a21',
  cherry: '#b92c2c',
  mustard: '#cea257',
  creamSand: '#d1bf9a',
  vanillaMist: '#e5e0cd',
  berryMuted: '#8a2430',
  textMuted: '#6b5a58',
  midBerryCherry: '#912527',
  midMustardVanilla: '#d8c8b2',
  chromeSand: '#c9b896',
  chromeDeep: '#b8a684',
  vanillaWash: '#f0ebe0',
} as const

const POMEGRANATE_REF = '/theme-refs/pomegranate-palette.png'

/**
 * 赫の果実 — Pure Noir, Dark Cherry, Passion Red, Dusty Rose, Rose Milk.
 */
export const pomegranatePalette = {
  noir: '#000000',
  darkCherry: '#47050b',
  passion: '#970000',
  rose: '#b5565a',
  roseMilk: '#f5e9e0',
  cherryMuted: '#5c1822',
  textMutedLight: '#6b4a50',
  textMutedDark: '#a89896',
  midPassionRose: '#a82b2d',
  midCherryRose: '#7e2b35',
  chromeRose: '#e8d8ce',
  chromeDeep: '#d4c2b8',
  darkCanvas: '#0f0608',
  darkCanvasLift: '#160a0c',
  milkWash: '#efe8e4',
} as const

const STRAWBERRY_REF = '/theme-refs/strawberry-palette.png'

/**
 * Strawberry board — Deep Maroon, Cherry Red, Moss Green, Lime Green, Soft Butter.
 */
export const strawberryPalette = {
  maroon: '#610000',
  cherry: '#ad1f07',
  moss: '#667d01',
  lime: '#9eb200',
  butter: '#eaeaaa',
  maroonMuted: '#6b2a20',
  mossMuted: '#556b02',
  textMuted: '#5a5a48',
  midMaroonCherry: '#871008',
  midMossButter: '#a8b456',
  midButterLime: '#c4cc55',
  chromeButter: '#dedeb8',
  chromeDeep: '#d0d0a8',
  butterWash: '#f2f2dc',
} as const

/**
 * Custom Tomato theme — Pear / Tomato / Honey / Sage.
 * Hex notes from your message (normalized to 6-digit #RRGGBB):
 * - Pear `C30A3` → `#c3a503` (golden pear; 5-char input completed)
 * - Tomato `C6463` → `#c66463` (dusty tomato)
 * - Honey `224C599` → `#f2c599` (amber honey; reads like a missing leading `F`)
 * - Sage `9AA98` → `#9aa985` (muted sage; 5-char input completed)
 */
export const tomatoPalette = {
  pear: '#c3a503',
  tomato: '#c66463',
  honey: '#f2c599',
  sage: '#9aa985',
  tomatoMuted: '#a85553',
  textMuted: '#6b5e4a',
  midTomatoPear: '#b5852b',
  midSagePear: '#b1a894',
  chromeHoney: '#e8d5a8',
} as const

/** Tomato 2 — exact swatches you provided */
export const tomato2Palette = {
  sage: '#929e6c',
  honey: '#f9cd90',
  tomato: '#c05123',
  pear: '#f69f2b',
  tomatoMuted: '#9d451e',
  textMuted: '#6a5c45',
  midSagePear: '#c9a34c',
  chromeHoney: '#f0d9a8',
} as const

/**
 * Butter-to-bronze stack — Cream / Lemon / Butter / Daffodil / Gold / Honey / Mustard / Amber / Maize / Bronze.
 * Derived from your reference swatches; tuned for readable ink + warm accents.
 */
export const butterStackPalette = {
  cream: '#f7f0d7',
  lemon: '#f4e6a1',
  butter: '#f0d25a',
  daffodil: '#e2bf2f',
  gold: '#c89f22',
  honey: '#b7841a',
  mustard: '#9f6d16',
  amber: '#865a13',
  maize: '#6a4710',
  bronze: '#4a3010',
  chrome: '#efe4c9',
  surface: '#fffdf6',
  surfaceHoney: '#fff7de',
  textMuted: '#7a6953',
  border: '#d8caa6',
} as const

/**
 * Shades of Sea — Ice / Aqua / Teal / Ocean / Azure / Cobalt / Aegean / Navy / Deep.
 * Tuned for crisp light surfaces with deep ocean ink and cool aqua accents.
 */
export const seaStackPalette = {
  ice: '#d6eee6',
  aqua: '#bfe3da',
  teal: '#4aa2a4',
  ocean: '#1f6f83',
  azure: '#1a4f6b',
  cobalt: '#133a5a',
  aegean: '#0f2c4a',
  navy: '#0b1f35',
  deep: '#071528',
  pageBg: '#f4efe5',
  chrome: '#e7e0d4',
  surface: '#fffdf8',
  surfaceHoney: '#f7fbfa',
  textMuted: '#5b6b71',
  border: '#cfd8d3',
} as const

/**
 * Neon Noir Blues — Desire / Dark Purple / Dark Cerulean / Medium Persian Blue / Rich Electric Blue.
 * Hex values are taken directly from your reference image.
 */
export const neonNoirBluePalette = {
  desire: '#ea404d',
  darkPurple: '#311131',
  darkCerulean: '#12447e',
  mediumPersianBlue: '#0663aa',
  richElectricBlue: '#0e92d2',
  pageBg: '#f4efe5',
  chrome: '#e7e0d4',
  surface: '#fffdf8',
  surfaceHoney: '#f7fbfa',
  textMuted: '#5b6b71',
  border: '#cfd8d3',
} as const

/** Legacy id from earlier builds → keeps localStorage working */
const LEGACY_THEME_IDS: Record<string, string> = {
  botanical: 'pear-tomato-original',
}

/** Add new entries here after we extract palettes from your reference images */
export const themes: ThemeDefinition[] = [
  {
    id: 'default',
    label: 'Default',
    vars: {
      cream: '#fdfbf7',
      navy: '#1a2744',
      navyMuted: '#2d3f5c',
      orange: '#e86b2b',
      orangeSoft: '#ff8f4a',
      textMuted: '#6b7280',
      reorderFrom: '#2b4a8f',
      reorderTo: '#6ba3f5',
      liveFrom: '#e86b2b',
      liveVia: '#f0a038',
      liveTo: '#f5c542',
      blindGlow: 'rgba(232, 107, 43, 0.55)',
      chrome: '#ebe8e2',
    },
  },
  /* ─── Pear & Tomato family (same 4 swatches, different role assignments) ─── */
  {
    id: 'pear-tomato-original',
    label: 'Pear & Tomato Original',
    previewImage: PEAR_TOMATO_REF,
    vars: {
      cream: pearTomatoPalette.crema,
      navy: pearTomatoPalette.darkSage,
      navyMuted: pearTomatoPalette.darkSageMuted,
      orange: pearTomatoPalette.tomato,
      orangeSoft: pearTomatoPalette.pear,
      textMuted: pearTomatoPalette.textMutedWarm,
      reorderFrom: pearTomatoPalette.tomato,
      reorderTo: pearTomatoPalette.pear,
      liveFrom: pearTomatoPalette.pear,
      liveVia: pearTomatoPalette.midGold,
      liveTo: pearTomatoPalette.tomato,
      blindGlow: 'rgba(197, 79, 45, 0.5)',
      chrome: pearTomatoPalette.chromeDeeperCrema,
    },
  },
  {
    id: 'pear-tomato-1',
    label: 'Pear & Tomato 1',
    previewImage: PEAR_TOMATO_REF,
    vars: {
      /* Pear as hero accent, tomato secondary; warm brown ink */
      cream: pearTomatoPalette.crema,
      navy: pearTomatoPalette.darkTomato,
      navyMuted: pearTomatoPalette.darkTomatoMuted,
      orange: pearTomatoPalette.pear,
      orangeSoft: pearTomatoPalette.tomato,
      textMuted: pearTomatoPalette.textMutedWarm,
      reorderFrom: pearTomatoPalette.pear,
      reorderTo: pearTomatoPalette.tomato,
      liveFrom: pearTomatoPalette.tomato,
      liveVia: pearTomatoPalette.midTomatoPear,
      liveTo: pearTomatoPalette.pear,
      blindGlow: 'rgba(238, 191, 67, 0.45)',
      chrome: pearTomatoPalette.chromePearTint,
    },
  },
  {
    id: 'pear-tomato-2',
    label: 'Pear & Tomato 2',
    previewImage: PEAR_TOMATO_REF,
    vars: {
      /* Mint-forward accents; pear lifts CTAs; cool green ink */
      cream: pearTomatoPalette.crema,
      navy: pearTomatoPalette.darkMint,
      navyMuted: pearTomatoPalette.darkMintMuted,
      orange: pearTomatoPalette.mint,
      orangeSoft: pearTomatoPalette.pear,
      textMuted: pearTomatoPalette.textMutedCool,
      reorderFrom: pearTomatoPalette.mint,
      reorderTo: pearTomatoPalette.pear,
      liveFrom: pearTomatoPalette.pear,
      liveVia: pearTomatoPalette.midMintPear,
      liveTo: pearTomatoPalette.mint,
      blindGlow: 'rgba(148, 179, 138, 0.5)',
      chrome: pearTomatoPalette.chromeMintTint,
    },
  },
  {
    id: 'pear-tomato-3',
    label: 'Pear & Tomato 3',
    previewImage: PEAR_TOMATO_REF,
    vars: {
      /* Tomato primary, mint as soft partner (pear in live strip) */
      cream: pearTomatoPalette.crema,
      navy: pearTomatoPalette.darkSage,
      navyMuted: pearTomatoPalette.darkSageMuted,
      orange: pearTomatoPalette.tomato,
      orangeSoft: pearTomatoPalette.mint,
      textMuted: pearTomatoPalette.textMutedWarm,
      reorderFrom: pearTomatoPalette.tomato,
      reorderTo: pearTomatoPalette.mint,
      liveFrom: pearTomatoPalette.mint,
      liveVia: pearTomatoPalette.midMintPear,
      liveTo: pearTomatoPalette.tomato,
      blindGlow: 'rgba(197, 79, 45, 0.5)',
      chrome: pearTomatoPalette.chromeSageFrame,
    },
  },
  {
    id: 'pear-tomato-4',
    label: 'Pear & Tomato 4',
    previewImage: PEAR_TOMATO_REF,
    vars: {
      /* Mint-tinted canvas + frame; tomato/pear gradients reordered */
      cream: '#eef4ea',
      navy: pearTomatoPalette.darkSage,
      navyMuted: pearTomatoPalette.darkSageMuted,
      orange: pearTomatoPalette.tomato,
      orangeSoft: pearTomatoPalette.pear,
      textMuted: pearTomatoPalette.textMutedCool,
      reorderFrom: pearTomatoPalette.pear,
      reorderTo: pearTomatoPalette.mint,
      liveFrom: pearTomatoPalette.tomato,
      liveVia: pearTomatoPalette.pear,
      liveTo: pearTomatoPalette.mint,
      blindGlow: 'rgba(197, 79, 45, 0.45)',
      chrome: pearTomatoPalette.chromeMintTint,
    },
  },
  /* ─── Bistro (Hot Paprika, Honeycomb, Biscuit, Crumpet) ─── */
  {
    id: 'bistro-original',
    label: 'Bistro Original',
    previewImage: BISTRO_REF,
    vars: {
      cream: bistroPalette.crumpet,
      navy: bistroPalette.darkPaprika,
      navyMuted: bistroPalette.darkPaprikaMuted,
      orange: bistroPalette.paprika,
      orangeSoft: bistroPalette.honeycomb,
      textMuted: bistroPalette.textMuted,
      reorderFrom: bistroPalette.paprika,
      reorderTo: bistroPalette.honeycomb,
      liveFrom: bistroPalette.honeycomb,
      liveVia: bistroPalette.midHoneyPaprika,
      liveTo: bistroPalette.paprika,
      blindGlow: 'rgba(181, 51, 36, 0.5)',
      chrome: bistroPalette.chromeBiscuit,
    },
  },
  {
    id: 'bistro-1',
    label: 'Bistro 1',
    previewImage: BISTRO_REF,
    vars: {
      /* Honeycomb as hero accent; paprika secondary */
      cream: bistroPalette.crumpet,
      navy: bistroPalette.darkWarmBrown,
      navyMuted: bistroPalette.darkWarmBrownMuted,
      orange: bistroPalette.honeycomb,
      orangeSoft: bistroPalette.paprika,
      textMuted: bistroPalette.textMuted,
      reorderFrom: bistroPalette.honeycomb,
      reorderTo: bistroPalette.paprika,
      liveFrom: bistroPalette.paprika,
      liveVia: bistroPalette.midHoneyPaprika,
      liveTo: bistroPalette.honeycomb,
      blindGlow: 'rgba(229, 166, 87, 0.45)',
      chrome: bistroPalette.chromeDeeper,
    },
  },
  {
    id: 'bistro-2',
    label: 'Bistro 2',
    previewImage: BISTRO_REF,
    vars: {
      /* Biscuit in CTAs + live strip; paprika primary */
      cream: bistroPalette.crumpet,
      navy: bistroPalette.darkPaprika,
      navyMuted: bistroPalette.darkPaprikaMuted,
      orange: bistroPalette.paprika,
      orangeSoft: bistroPalette.biscuit,
      textMuted: bistroPalette.textMuted,
      reorderFrom: bistroPalette.paprika,
      reorderTo: bistroPalette.biscuit,
      liveFrom: bistroPalette.biscuit,
      liveVia: bistroPalette.honeycomb,
      liveTo: bistroPalette.paprika,
      blindGlow: 'rgba(181, 51, 36, 0.48)',
      chrome: bistroPalette.chromeDeeper,
    },
  },
  {
    id: 'bistro-3',
    label: 'Bistro 3',
    previewImage: BISTRO_REF,
    vars: {
      /* Honeycomb primary, biscuit soft — paprika anchors text + glow */
      cream: bistroPalette.crumpet,
      navy: bistroPalette.darkPaprika,
      navyMuted: bistroPalette.darkPaprikaMuted,
      orange: bistroPalette.honeycomb,
      orangeSoft: bistroPalette.biscuit,
      textMuted: bistroPalette.textMuted,
      reorderFrom: bistroPalette.honeycomb,
      reorderTo: bistroPalette.biscuit,
      liveFrom: bistroPalette.paprika,
      liveVia: bistroPalette.midHoneyPaprika,
      liveTo: bistroPalette.honeycomb,
      blindGlow: 'rgba(181, 51, 36, 0.4)',
      chrome: bistroPalette.chromeBiscuit,
    },
  },
  {
    id: 'bistro-4',
    label: 'Bistro 4',
    previewImage: BISTRO_REF,
    vars: {
      /* Biscuit-wash canvas; gradients cycle paprika → honeycomb → biscuit */
      cream: bistroPalette.creamBiscuitWash,
      navy: bistroPalette.darkPaprika,
      navyMuted: bistroPalette.darkPaprikaMuted,
      orange: bistroPalette.paprika,
      orangeSoft: bistroPalette.honeycomb,
      textMuted: bistroPalette.textMuted,
      reorderFrom: bistroPalette.honeycomb,
      reorderTo: bistroPalette.paprika,
      liveFrom: bistroPalette.paprika,
      liveVia: bistroPalette.honeycomb,
      liveTo: bistroPalette.biscuit,
      blindGlow: 'rgba(181, 51, 36, 0.45)',
      chrome: bistroPalette.chromeDeeper,
    },
  },
  /* ─── Sunshine (6 swatches — rotated through UI roles) ─── */
  {
    id: 'sunshine-original',
    label: 'Sunshine Original',
    previewImage: SUNSHINE_REF,
    vars: {
      cream: sunshinePalette.cream,
      navy: sunshinePalette.forest,
      navyMuted: sunshinePalette.forestMuted,
      orange: sunshinePalette.carrot,
      orangeSoft: sunshinePalette.sunshine,
      textMuted: sunshinePalette.textMuted,
      reorderFrom: sunshinePalette.carrot,
      reorderTo: sunshinePalette.sunshine,
      liveFrom: sunshinePalette.sunshine,
      liveVia: sunshinePalette.midSunshineCarrot,
      liveTo: sunshinePalette.tomato,
      blindGlow: 'rgba(249, 96, 21, 0.5)',
      chrome: sunshinePalette.chromeCream,
    },
  },
  {
    id: 'sunshine-1',
    label: 'Sunshine 1',
    previewImage: SUNSHINE_REF,
    vars: {
      /* Tomato Burst primary, Crisp Carrot partner */
      cream: sunshinePalette.cream,
      navy: sunshinePalette.forest,
      navyMuted: sunshinePalette.forestMuted,
      orange: sunshinePalette.tomato,
      orangeSoft: sunshinePalette.carrot,
      textMuted: sunshinePalette.textMuted,
      reorderFrom: sunshinePalette.tomato,
      reorderTo: sunshinePalette.carrot,
      liveFrom: sunshinePalette.carrot,
      liveVia: sunshinePalette.midCarrotTomato,
      liveTo: sunshinePalette.sunshine,
      blindGlow: 'rgba(213, 37, 24, 0.5)',
      chrome: sunshinePalette.chromeCream,
    },
  },
  {
    id: 'sunshine-2',
    label: 'Sunshine 2',
    previewImage: SUNSHINE_REF,
    vars: {
      /* Kiwi + Sunshine — forest ink */
      cream: sunshinePalette.cream,
      navy: sunshinePalette.forest,
      navyMuted: sunshinePalette.forestMuted,
      orange: sunshinePalette.kiwi,
      orangeSoft: sunshinePalette.sunshine,
      textMuted: sunshinePalette.textMuted,
      reorderFrom: sunshinePalette.kiwi,
      reorderTo: sunshinePalette.sunshine,
      liveFrom: sunshinePalette.sunshine,
      liveVia: sunshinePalette.midSunshineCarrot,
      liveTo: sunshinePalette.kiwi,
      blindGlow: 'rgba(154, 188, 5, 0.45)',
      chrome: sunshinePalette.chromeKiwiTint,
    },
  },
  {
    id: 'sunshine-3',
    label: 'Sunshine 3',
    previewImage: SUNSHINE_REF,
    vars: {
      /* Sunshine as hero accent; Kiwi soft; tomato in live strip */
      cream: sunshinePalette.cream,
      navy: sunshinePalette.forest,
      navyMuted: sunshinePalette.forestMuted,
      orange: sunshinePalette.sunshine,
      orangeSoft: sunshinePalette.kiwi,
      textMuted: sunshinePalette.textMuted,
      reorderFrom: sunshinePalette.sunshine,
      reorderTo: sunshinePalette.tomato,
      liveFrom: sunshinePalette.tomato,
      liveVia: sunshinePalette.carrot,
      liveTo: sunshinePalette.sunshine,
      blindGlow: 'rgba(255, 201, 38, 0.4)',
      chrome: sunshinePalette.chromeCream,
    },
  },
  {
    id: 'sunshine-4',
    label: 'Sunshine 4',
    previewImage: SUNSHINE_REF,
    vars: {
      /* Warm wash canvas; carrot ↔ tomato CTAs; kiwi closes live strip */
      cream: sunshinePalette.creamSunshineWash,
      navy: sunshinePalette.darkTomatoInk,
      navyMuted: sunshinePalette.darkTomatoInkMuted,
      orange: sunshinePalette.carrot,
      orangeSoft: sunshinePalette.tomato,
      textMuted: sunshinePalette.textMuted,
      reorderFrom: sunshinePalette.carrot,
      reorderTo: sunshinePalette.tomato,
      liveFrom: sunshinePalette.kiwi,
      liveVia: sunshinePalette.sunshine,
      liveTo: sunshinePalette.carrot,
      blindGlow: 'rgba(249, 96, 21, 0.45)',
      chrome: sunshinePalette.chromeKiwiTint,
    },
  },
  /* ─── Honey / 蜜色の詩 (artisan honey & wood) ─── */
  {
    id: 'honey-original',
    label: 'Honey Original',
    previewImage: HONEY_REF,
    vars: {
      /* Sunlit wash base; cocoa ink; Burnt Red → Honey Gold accents; live echoes board G2 */
      cream: honeyPalette.creamSoft,
      navy: honeyPalette.cocoa,
      navyMuted: honeyPalette.cocoaMuted,
      orange: honeyPalette.burnt,
      orangeSoft: honeyPalette.gold,
      textMuted: honeyPalette.textMuted,
      reorderFrom: honeyPalette.burnt,
      reorderTo: honeyPalette.sunlit,
      liveFrom: honeyPalette.sunlit,
      liveVia: honeyPalette.midGoldSunlit,
      liveTo: honeyPalette.burnt,
      blindGlow: 'rgba(126, 23, 13, 0.45)',
      chrome: honeyPalette.chromeTan,
    },
  },
  {
    id: 'honey-1',
    label: 'Honey 1',
    previewImage: HONEY_REF,
    vars: {
      /* Honey Gold hero; burnt red partner (G1-style energy on CTA) */
      cream: honeyPalette.creamSoft,
      navy: honeyPalette.cocoa,
      navyMuted: honeyPalette.cocoaMuted,
      orange: honeyPalette.gold,
      orangeSoft: honeyPalette.burnt,
      textMuted: honeyPalette.textMuted,
      reorderFrom: honeyPalette.gold,
      reorderTo: honeyPalette.sunlit,
      liveFrom: honeyPalette.burnt,
      liveVia: honeyPalette.midBurntGold,
      liveTo: honeyPalette.sunlit,
      blindGlow: 'rgba(185, 118, 33, 0.4)',
      chrome: honeyPalette.chromeTan,
    },
  },
  {
    id: 'honey-2',
    label: 'Honey 2',
    previewImage: HONEY_REF,
    vars: {
      /* Muted Tan as soft accent; burnt primary */
      cream: honeyPalette.creamSoft,
      navy: honeyPalette.cocoa,
      navyMuted: honeyPalette.cocoaMuted2,
      orange: honeyPalette.burnt,
      orangeSoft: honeyPalette.tan,
      textMuted: honeyPalette.textMuted,
      reorderFrom: honeyPalette.burnt,
      reorderTo: honeyPalette.tan,
      liveFrom: honeyPalette.tan,
      liveVia: honeyPalette.gold,
      liveTo: honeyPalette.burnt,
      blindGlow: 'rgba(126, 23, 13, 0.48)',
      chrome: honeyPalette.tan,
    },
  },
  {
    id: 'honey-3',
    label: 'Honey 3',
    previewImage: HONEY_REF,
    vars: {
      /* Cocoa → Gold gradient feel: gold-forward CTAs, sunlit highlight */
      cream: honeyPalette.sunlit,
      navy: honeyPalette.cocoa,
      navyMuted: honeyPalette.cocoaMuted,
      orange: honeyPalette.gold,
      orangeSoft: honeyPalette.sunlit,
      textMuted: honeyPalette.textMuted,
      reorderFrom: honeyPalette.cocoa,
      reorderTo: honeyPalette.gold,
      liveFrom: honeyPalette.sunlit,
      liveVia: honeyPalette.tan,
      liveTo: honeyPalette.gold,
      blindGlow: 'rgba(55, 33, 17, 0.35)',
      chrome: honeyPalette.chromeDeep,
    },
  },
  {
    id: 'honey-4',
    label: 'Honey 4',
    previewImage: HONEY_REF,
    vars: {
      /* Pale sunlit canvas; G3 live: sunlit → tan; CTA sunlit → burnt */
      cream: honeyPalette.creamSunlitWash,
      navy: honeyPalette.cocoa,
      navyMuted: honeyPalette.cocoaMuted,
      orange: honeyPalette.burnt,
      orangeSoft: honeyPalette.tan,
      textMuted: honeyPalette.textMuted,
      reorderFrom: honeyPalette.sunlit,
      reorderTo: honeyPalette.burnt,
      liveFrom: honeyPalette.sunlit,
      liveVia: honeyPalette.midGoldSunlit,
      liveTo: honeyPalette.tan,
      blindGlow: 'rgba(126, 23, 13, 0.4)',
      chrome: honeyPalette.chromeTan,
    },
  },
  /* ─── Marmalade / toast palette ─── */
  {
    id: 'marmalade-original',
    label: 'Marmalade Original',
    previewImage: MARMALADE_REF,
    vars: {
      /* Board G1 on CTA (caramel → tangy); live echoes G2 (burnt → honey) */
      cream: marmaladePalette.honeyMilk,
      navy: marmaladePalette.deepCaramel,
      navyMuted: marmaladePalette.caramelMuted,
      orange: marmaladePalette.tangy,
      orangeSoft: marmaladePalette.burnt,
      textMuted: marmaladePalette.textMuted,
      reorderFrom: marmaladePalette.deepCaramel,
      reorderTo: marmaladePalette.tangy,
      liveFrom: marmaladePalette.burnt,
      liveVia: marmaladePalette.midTangyBurnt,
      liveTo: marmaladePalette.honeyMilk,
      blindGlow: 'rgba(253, 90, 1, 0.4)',
      chrome: marmaladePalette.chromeCaramel,
    },
  },
  {
    id: 'marmalade-1',
    label: 'Marmalade 1',
    previewImage: MARMALADE_REF,
    vars: {
      /* Tangy hero; Caramel Milk soft; live G3 (honey → caramel milk) */
      cream: marmaladePalette.honeyMilk,
      navy: marmaladePalette.deepCaramel,
      navyMuted: marmaladePalette.caramelMuted,
      orange: marmaladePalette.tangy,
      orangeSoft: marmaladePalette.caramelMilk,
      textMuted: marmaladePalette.textMuted,
      reorderFrom: marmaladePalette.tangy,
      reorderTo: marmaladePalette.honeyMilk,
      liveFrom: marmaladePalette.honeyMilk,
      liveVia: marmaladePalette.midHoneyCaramel,
      liveTo: marmaladePalette.caramelMilk,
      blindGlow: 'rgba(253, 90, 1, 0.35)',
      chrome: marmaladePalette.chromeCaramel,
    },
  },
  {
    id: 'marmalade-2',
    label: 'Marmalade 2',
    previewImage: MARMALADE_REF,
    vars: {
      /* Burnt Orange primary; G2-style CTA (burnt → honey) */
      cream: marmaladePalette.honeyMilk,
      navy: marmaladePalette.deepCaramel,
      navyMuted: marmaladePalette.caramelMuted,
      orange: marmaladePalette.burnt,
      orangeSoft: marmaladePalette.honeyMilk,
      textMuted: marmaladePalette.textMuted,
      reorderFrom: marmaladePalette.burnt,
      reorderTo: marmaladePalette.honeyMilk,
      liveFrom: marmaladePalette.deepCaramel,
      liveVia: marmaladePalette.caramelMilk,
      liveTo: marmaladePalette.tangy,
      blindGlow: 'rgba(206, 92, 3, 0.45)',
      chrome: marmaladePalette.chromeDeep,
    },
  },
  {
    id: 'marmalade-3',
    label: 'Marmalade 3',
    previewImage: MARMALADE_REF,
    vars: {
      /* Softer canvas; caramel milk in gradients; tangy peak */
      cream: marmaladePalette.creamWash,
      navy: marmaladePalette.deepCaramel,
      navyMuted: marmaladePalette.caramelMuted,
      orange: marmaladePalette.tangy,
      orangeSoft: marmaladePalette.caramelMilk,
      textMuted: marmaladePalette.textMuted,
      reorderFrom: marmaladePalette.caramelMilk,
      reorderTo: marmaladePalette.tangy,
      liveFrom: marmaladePalette.honeyMilk,
      liveVia: marmaladePalette.midHoneyCaramel,
      liveTo: marmaladePalette.burnt,
      blindGlow: 'rgba(209, 153, 117, 0.35)',
      chrome: marmaladePalette.chromeCaramel,
    },
  },
  {
    id: 'marmalade-4',
    label: 'Marmalade 4',
    previewImage: MARMALADE_REF,
    vars: {
      /* Burnt ↔ tangy swap; CTA honey → caramel (G3); live citrus close */
      cream: marmaladePalette.creamWash,
      navy: marmaladePalette.deepCaramel,
      navyMuted: marmaladePalette.caramelMuted,
      orange: marmaladePalette.burnt,
      orangeSoft: marmaladePalette.tangy,
      textMuted: marmaladePalette.textMuted,
      reorderFrom: marmaladePalette.honeyMilk,
      reorderTo: marmaladePalette.caramelMilk,
      liveFrom: marmaladePalette.tangy,
      liveVia: marmaladePalette.burnt,
      liveTo: marmaladePalette.honeyMilk,
      blindGlow: 'rgba(206, 92, 3, 0.4)',
      chrome: marmaladePalette.chromeDeep,
    },
  },
  /* ─── Jewel / strawberry dessert (午後3時の宝石) ─── */
  {
    id: 'jewel-original',
    label: 'Jewel Original',
    previewImage: JEWEL_REF,
    vars: {
      /* Vanilla base; G1 CTA (berry → cherry); live G3 (mustard → vanilla) */
      cream: jewelPalette.vanillaMist,
      navy: jewelPalette.berryWine,
      navyMuted: jewelPalette.berryMuted,
      orange: jewelPalette.cherry,
      orangeSoft: jewelPalette.mustard,
      textMuted: jewelPalette.textMuted,
      reorderFrom: jewelPalette.berryWine,
      reorderTo: jewelPalette.cherry,
      liveFrom: jewelPalette.mustard,
      liveVia: jewelPalette.midMustardVanilla,
      liveTo: jewelPalette.vanillaMist,
      blindGlow: 'rgba(185, 44, 44, 0.45)',
      chrome: jewelPalette.chromeSand,
    },
  },
  {
    id: 'jewel-1',
    label: 'Jewel 1',
    previewImage: JEWEL_REF,
    vars: {
      /* Cherry → mustard CTA; live echoes G2 (sand → wine family) */
      cream: jewelPalette.vanillaMist,
      navy: jewelPalette.berryWine,
      navyMuted: jewelPalette.berryMuted,
      orange: jewelPalette.cherry,
      orangeSoft: jewelPalette.mustard,
      textMuted: jewelPalette.textMuted,
      reorderFrom: jewelPalette.cherry,
      reorderTo: jewelPalette.mustard,
      liveFrom: jewelPalette.creamSand,
      liveVia: jewelPalette.midBerryCherry,
      liveTo: jewelPalette.cherry,
      blindGlow: 'rgba(185, 44, 44, 0.4)',
      chrome: jewelPalette.creamSand,
    },
  },
  {
    id: 'jewel-2',
    label: 'Jewel 2',
    previewImage: JEWEL_REF,
    vars: {
      /* Softer wash; Cream Sand as soft accent */
      cream: jewelPalette.vanillaWash,
      navy: jewelPalette.berryWine,
      navyMuted: jewelPalette.berryMuted,
      orange: jewelPalette.cherry,
      orangeSoft: jewelPalette.creamSand,
      textMuted: jewelPalette.textMuted,
      reorderFrom: jewelPalette.cherry,
      reorderTo: jewelPalette.vanillaMist,
      liveFrom: jewelPalette.berryWine,
      liveVia: jewelPalette.cherry,
      liveTo: jewelPalette.mustard,
      blindGlow: 'rgba(108, 26, 33, 0.35)',
      chrome: jewelPalette.chromeSand,
    },
  },
  {
    id: 'jewel-3',
    label: 'Jewel 3',
    previewImage: JEWEL_REF,
    vars: {
      /* Golden Mustard hero; G3-style CTA (mustard → vanilla) */
      cream: jewelPalette.vanillaMist,
      navy: jewelPalette.berryWine,
      navyMuted: jewelPalette.berryMuted,
      orange: jewelPalette.mustard,
      orangeSoft: jewelPalette.cherry,
      textMuted: jewelPalette.textMuted,
      reorderFrom: jewelPalette.mustard,
      reorderTo: jewelPalette.vanillaMist,
      liveFrom: jewelPalette.cherry,
      liveVia: jewelPalette.midMustardVanilla,
      liveTo: jewelPalette.mustard,
      blindGlow: 'rgba(206, 162, 87, 0.4)',
      chrome: jewelPalette.chromeDeep,
    },
  },
  {
    id: 'jewel-4',
    label: 'Jewel 4',
    previewImage: JEWEL_REF,
    vars: {
      /* G2 on CTA (cream sand → berry); cherry / mustard live */
      cream: jewelPalette.vanillaWash,
      navy: jewelPalette.berryWine,
      navyMuted: jewelPalette.berryMuted,
      orange: jewelPalette.cherry,
      orangeSoft: jewelPalette.mustard,
      textMuted: jewelPalette.textMuted,
      reorderFrom: jewelPalette.creamSand,
      reorderTo: jewelPalette.berryWine,
      liveFrom: jewelPalette.cherry,
      liveVia: jewelPalette.mustard,
      liveTo: jewelPalette.vanillaMist,
      blindGlow: 'rgba(185, 44, 44, 0.38)',
      chrome: jewelPalette.chromeDeep,
    },
  },
  /* ─── Pomegranate / 赫の果実 (moody red fruit) ─── */
  {
    id: 'pomegranate-original',
    label: 'Pomegranate Original',
    previewImage: POMEGRANATE_REF,
    vars: {
      /* Rose Milk canvas; Dark Cherry ink; CTA cherry → passion; live G2 */
      cream: pomegranatePalette.roseMilk,
      navy: pomegranatePalette.darkCherry,
      navyMuted: pomegranatePalette.cherryMuted,
      orange: pomegranatePalette.passion,
      orangeSoft: pomegranatePalette.rose,
      textMuted: pomegranatePalette.textMutedLight,
      reorderFrom: pomegranatePalette.darkCherry,
      reorderTo: pomegranatePalette.passion,
      liveFrom: pomegranatePalette.passion,
      liveVia: pomegranatePalette.midPassionRose,
      liveTo: pomegranatePalette.roseMilk,
      blindGlow: 'rgba(151, 0, 0, 0.45)',
      chrome: pomegranatePalette.chromeRose,
    },
  },
  {
    id: 'pomegranate-1',
    label: 'Pomegranate 1',
    previewImage: POMEGRANATE_REF,
    vars: {
      /* Dark canvas: near-noir bg, Rose Milk headings; premium “dark mode” */
      cream: pomegranatePalette.darkCanvas,
      navy: pomegranatePalette.roseMilk,
      navyMuted: pomegranatePalette.chromeDeep,
      orange: pomegranatePalette.passion,
      orangeSoft: pomegranatePalette.rose,
      textMuted: pomegranatePalette.textMutedDark,
      reorderFrom: pomegranatePalette.passion,
      reorderTo: pomegranatePalette.roseMilk,
      liveFrom: pomegranatePalette.darkCherry,
      liveVia: pomegranatePalette.midCherryRose,
      liveTo: pomegranatePalette.rose,
      blindGlow: 'rgba(151, 0, 0, 0.5)',
      chrome: pomegranatePalette.darkCanvasLift,
    },
  },
  {
    id: 'pomegranate-2',
    label: 'Pomegranate 2',
    previewImage: POMEGRANATE_REF,
    vars: {
      /* G1 CTA (noir → passion); live G3 (cherry → rose) */
      cream: pomegranatePalette.roseMilk,
      navy: pomegranatePalette.darkCherry,
      navyMuted: pomegranatePalette.cherryMuted,
      orange: pomegranatePalette.passion,
      orangeSoft: pomegranatePalette.rose,
      textMuted: pomegranatePalette.textMutedLight,
      reorderFrom: pomegranatePalette.noir,
      reorderTo: pomegranatePalette.passion,
      liveFrom: pomegranatePalette.darkCherry,
      liveVia: pomegranatePalette.midCherryRose,
      liveTo: pomegranatePalette.rose,
      blindGlow: 'rgba(0, 0, 0, 0.25)',
      chrome: pomegranatePalette.chromeDeep,
    },
  },
  {
    id: 'pomegranate-3',
    label: 'Pomegranate 3',
    previewImage: POMEGRANATE_REF,
    vars: {
      /* Noir ink on soft wash; passion-led UI */
      cream: pomegranatePalette.milkWash,
      navy: pomegranatePalette.noir,
      navyMuted: pomegranatePalette.cherryMuted,
      orange: pomegranatePalette.passion,
      orangeSoft: pomegranatePalette.rose,
      textMuted: pomegranatePalette.textMutedLight,
      reorderFrom: pomegranatePalette.passion,
      reorderTo: pomegranatePalette.roseMilk,
      liveFrom: pomegranatePalette.rose,
      liveVia: pomegranatePalette.midPassionRose,
      liveTo: pomegranatePalette.passion,
      blindGlow: 'rgba(151, 0, 0, 0.4)',
      chrome: pomegranatePalette.chromeRose,
    },
  },
  {
    id: 'pomegranate-4',
    label: 'Pomegranate 4',
    previewImage: POMEGRANATE_REF,
    vars: {
      /* Dusty Rose forward; CTA echoes G3 (cherry → rose) */
      cream: pomegranatePalette.roseMilk,
      navy: pomegranatePalette.darkCherry,
      navyMuted: pomegranatePalette.cherryMuted,
      orange: pomegranatePalette.rose,
      orangeSoft: pomegranatePalette.passion,
      textMuted: pomegranatePalette.textMutedLight,
      reorderFrom: pomegranatePalette.darkCherry,
      reorderTo: pomegranatePalette.rose,
      liveFrom: pomegranatePalette.passion,
      liveVia: pomegranatePalette.rose,
      liveTo: pomegranatePalette.roseMilk,
      blindGlow: 'rgba(181, 86, 90, 0.4)',
      chrome: pomegranatePalette.chromeDeep,
    },
  },
  /* ─── Strawberry (maroon / cherry / moss / lime on butter) ─── */
  {
    id: 'strawberry-original',
    label: 'Strawberry Original',
    previewImage: STRAWBERRY_REF,
    vars: {
      /* Soft Butter base; G1 CTA; live G2 (moss → butter) */
      cream: strawberryPalette.butter,
      navy: strawberryPalette.maroon,
      navyMuted: strawberryPalette.maroonMuted,
      orange: strawberryPalette.cherry,
      orangeSoft: strawberryPalette.lime,
      textMuted: strawberryPalette.textMuted,
      reorderFrom: strawberryPalette.maroon,
      reorderTo: strawberryPalette.cherry,
      liveFrom: strawberryPalette.moss,
      liveVia: strawberryPalette.midMossButter,
      liveTo: strawberryPalette.butter,
      blindGlow: 'rgba(173, 31, 7, 0.4)',
      chrome: strawberryPalette.chromeButter,
    },
  },
  {
    id: 'strawberry-1',
    label: 'Strawberry 1',
    previewImage: STRAWBERRY_REF,
    vars: {
      /* Lime hero; G3 CTA (butter → lime); cherry in live */
      cream: strawberryPalette.butter,
      navy: strawberryPalette.maroon,
      navyMuted: strawberryPalette.maroonMuted,
      orange: strawberryPalette.lime,
      orangeSoft: strawberryPalette.cherry,
      textMuted: strawberryPalette.textMuted,
      reorderFrom: strawberryPalette.butter,
      reorderTo: strawberryPalette.lime,
      liveFrom: strawberryPalette.cherry,
      liveVia: strawberryPalette.midMaroonCherry,
      liveTo: strawberryPalette.moss,
      blindGlow: 'rgba(158, 178, 0, 0.4)',
      chrome: strawberryPalette.chromeButter,
    },
  },
  {
    id: 'strawberry-2',
    label: 'Strawberry 2',
    previewImage: STRAWBERRY_REF,
    vars: {
      /* Moss-forward; G2 CTA (moss → butter) */
      cream: strawberryPalette.butter,
      navy: strawberryPalette.moss,
      navyMuted: strawberryPalette.mossMuted,
      orange: strawberryPalette.moss,
      orangeSoft: strawberryPalette.lime,
      textMuted: strawberryPalette.textMuted,
      reorderFrom: strawberryPalette.moss,
      reorderTo: strawberryPalette.butter,
      liveFrom: strawberryPalette.maroon,
      liveVia: strawberryPalette.cherry,
      liveTo: strawberryPalette.lime,
      blindGlow: 'rgba(102, 125, 1, 0.35)',
      chrome: strawberryPalette.chromeDeep,
    },
  },
  {
    id: 'strawberry-3',
    label: 'Strawberry 3',
    previewImage: STRAWBERRY_REF,
    vars: {
      /* Lighter wash; moss ink; cherry ↔ lime energy */
      cream: strawberryPalette.butterWash,
      navy: strawberryPalette.moss,
      navyMuted: strawberryPalette.mossMuted,
      orange: strawberryPalette.cherry,
      orangeSoft: strawberryPalette.butter,
      textMuted: strawberryPalette.textMuted,
      reorderFrom: strawberryPalette.cherry,
      reorderTo: strawberryPalette.lime,
      liveFrom: strawberryPalette.butter,
      liveVia: strawberryPalette.midButterLime,
      liveTo: strawberryPalette.lime,
      blindGlow: 'rgba(173, 31, 7, 0.35)',
      chrome: strawberryPalette.chromeButter,
    },
  },
  {
    id: 'strawberry-4',
    label: 'Strawberry 4',
    previewImage: STRAWBERRY_REF,
    vars: {
      /* Lime primary, moss soft; live closes on cherry */
      cream: strawberryPalette.butter,
      navy: strawberryPalette.maroon,
      navyMuted: strawberryPalette.maroonMuted,
      orange: strawberryPalette.lime,
      orangeSoft: strawberryPalette.moss,
      textMuted: strawberryPalette.textMuted,
      reorderFrom: strawberryPalette.lime,
      reorderTo: strawberryPalette.cherry,
      liveFrom: strawberryPalette.moss,
      liveVia: strawberryPalette.butter,
      liveTo: strawberryPalette.cherry,
      blindGlow: 'rgba(158, 178, 0, 0.38)',
      chrome: strawberryPalette.chromeDeep,
    },
  },
  {
    id: 'tomato',
    label: 'Tomato',
    vars: {
      /* Honey canvas; tomato for headings, active chips, tab labels & primary accents */
      cream: tomatoPalette.honey,
      navy: tomatoPalette.tomato,
      navyMuted: tomatoPalette.tomatoMuted,
      orange: tomatoPalette.tomato,
      orangeSoft: tomatoPalette.pear,
      textMuted: tomatoPalette.textMuted,
      reorderFrom: tomatoPalette.tomato,
      reorderTo: tomatoPalette.pear,
      liveFrom: tomatoPalette.sage,
      liveVia: tomatoPalette.midSagePear,
      liveTo: tomatoPalette.honey,
      blindGlow: 'rgba(198, 100, 99, 0.45)',
      chrome: tomatoPalette.chromeHoney,
    },
  },
  {
    id: 'tomato-2',
    label: 'Tomato 2',
    vars: {
      cream: tomato2Palette.honey,
      navy: tomato2Palette.tomato,
      navyMuted: tomato2Palette.tomatoMuted,
      orange: tomato2Palette.tomato,
      orangeSoft: tomato2Palette.pear,
      textMuted: tomato2Palette.textMuted,
      reorderFrom: tomato2Palette.tomato,
      reorderTo: tomato2Palette.pear,
      liveFrom: tomato2Palette.sage,
      liveVia: tomato2Palette.midSagePear,
      liveTo: tomato2Palette.honey,
      blindGlow: 'rgba(192, 81, 35, 0.45)',
      chrome: tomato2Palette.chromeHoney,
    },
  },
  {
    id: 'tomato-3',
    label: 'Tomato 3',
    vars: {
      cream: '#f4f1ea',
      chrome: '#e6eae0',
      navy: '#3c3834',
      navyMuted: '#5c5651',
      orange: tomato2Palette.tomato,
      orangeSoft: tomato2Palette.pear,
      textMuted: '#6d665e',
      reorderFrom: tomato2Palette.tomato,
      reorderTo: tomato2Palette.tomato,
      liveFrom: tomato2Palette.tomato,
      liveVia: '#d45828',
      liveTo: tomato2Palette.tomato,
      blindGlow: 'rgba(246, 159, 43, 0.32)',
      pageBg: '#f4f1ea',
      surfaceCard: '#fffdf8',
      surfaceHoney: '#fef5e8',
      textPrimary: '#3c3834',
      textSecondary: '#6d665e',
      borderSubtle: '#d4d9c8',
      sageSoft: '#eef0ea',
      sageBorder: '#c5cbb8',
      navInactive: '#8a9378',
      pearAccent: tomato2Palette.pear,
      promoBg: '#4a5248',
      chipSelectedBg: tomato2Palette.tomato,
      liveBadge: tomato2Palette.tomato,
      cartBadge: tomato2Palette.pear,
      thumbRing: 'rgba(249, 205, 144, 0.45)',
      liveIconWell: 'rgba(255, 255, 255, 0.2)',
    },
  },
  {
    id: 'butter-stack',
    label: 'Butter Stack',
    vars: {
      cream: butterStackPalette.cream,
      chrome: butterStackPalette.chrome,
      navy: butterStackPalette.bronze,
      navyMuted: butterStackPalette.maize,
      orange: butterStackPalette.daffodil,
      orangeSoft: butterStackPalette.butter,
      textMuted: butterStackPalette.textMuted,
      reorderFrom: butterStackPalette.amber,
      reorderTo: butterStackPalette.gold,
      liveFrom: butterStackPalette.butter,
      liveVia: butterStackPalette.daffodil,
      liveTo: butterStackPalette.gold,
      blindGlow: 'rgba(226, 191, 47, 0.35)',
      pageBg: butterStackPalette.cream,
      surfaceCard: butterStackPalette.surface,
      surfaceHoney: butterStackPalette.surfaceHoney,
      textPrimary: butterStackPalette.bronze,
      textSecondary: butterStackPalette.textMuted,
      borderSubtle: butterStackPalette.border,
      sageSoft: butterStackPalette.lemon,
      sageBorder: butterStackPalette.border,
      navInactive: butterStackPalette.mustard,
      pearAccent: butterStackPalette.butter,
      promoBg: butterStackPalette.maize,
      chipSelectedBg: butterStackPalette.daffodil,
      liveBadge: butterStackPalette.daffodil,
      cartBadge: butterStackPalette.butter,
      thumbRing: 'rgba(74, 48, 16, 0.10)',
      liveIconWell: 'rgba(255, 255, 255, 0.18)',
    },
  },
  {
    id: 'sea-stack',
    label: 'Shades of Sea',
    vars: {
      cream: seaStackPalette.pageBg,
      chrome: seaStackPalette.chrome,
      navy: seaStackPalette.deep,
      navyMuted: seaStackPalette.navy,
      orange: seaStackPalette.ocean,
      orangeSoft: seaStackPalette.aqua,
      textMuted: seaStackPalette.textMuted,
      reorderFrom: seaStackPalette.azure,
      reorderTo: seaStackPalette.ocean,
      liveFrom: seaStackPalette.teal,
      liveVia: seaStackPalette.aqua,
      liveTo: seaStackPalette.ice,
      blindGlow: 'rgba(31, 111, 131, 0.26)',
      pageBg: seaStackPalette.pageBg,
      surfaceCard: seaStackPalette.surface,
      surfaceHoney: seaStackPalette.surfaceHoney,
      textPrimary: seaStackPalette.deep,
      textSecondary: seaStackPalette.textMuted,
      borderSubtle: seaStackPalette.border,
      sageSoft: seaStackPalette.ice,
      sageBorder: seaStackPalette.border,
      navInactive: seaStackPalette.cobalt,
      pearAccent: seaStackPalette.aqua,
      promoBg: seaStackPalette.aegean,
      chipSelectedBg: seaStackPalette.ocean,
      liveBadge: seaStackPalette.ocean,
      cartBadge: seaStackPalette.aqua,
      thumbRing: 'rgba(7, 21, 40, 0.10)',
      liveIconWell: 'rgba(255, 255, 255, 0.18)',
    },
  },
  {
    id: 'neon-noir-blue',
    label: 'Neon Noir Blue',
    vars: {
      cream: neonNoirBluePalette.pageBg,
      chrome: neonNoirBluePalette.chrome,
      navy: neonNoirBluePalette.darkPurple,
      navyMuted: neonNoirBluePalette.darkCerulean,
      orange: neonNoirBluePalette.richElectricBlue,
      orangeSoft: neonNoirBluePalette.desire,
      textMuted: neonNoirBluePalette.textMuted,
      reorderFrom: neonNoirBluePalette.darkCerulean,
      reorderTo: neonNoirBluePalette.richElectricBlue,
      liveFrom: neonNoirBluePalette.desire,
      liveVia: neonNoirBluePalette.richElectricBlue,
      liveTo: neonNoirBluePalette.mediumPersianBlue,
      blindGlow: 'rgba(14, 146, 210, 0.28)',
      pageBg: neonNoirBluePalette.pageBg,
      surfaceCard: neonNoirBluePalette.surface,
      surfaceHoney: neonNoirBluePalette.surfaceHoney,
      textPrimary: neonNoirBluePalette.darkPurple,
      textSecondary: neonNoirBluePalette.textMuted,
      borderSubtle: neonNoirBluePalette.border,
      sageSoft: neonNoirBluePalette.surfaceHoney,
      sageBorder: neonNoirBluePalette.border,
      navInactive: neonNoirBluePalette.mediumPersianBlue,
      pearAccent: neonNoirBluePalette.desire,
      promoBg: neonNoirBluePalette.darkCerulean,
      chipSelectedBg: neonNoirBluePalette.richElectricBlue,
      liveBadge: neonNoirBluePalette.desire,
      cartBadge: neonNoirBluePalette.desire,
      thumbRing: 'rgba(49, 17, 49, 0.10)',
      liveIconWell: 'rgba(255, 255, 255, 0.18)',
    },
  },
]

export const defaultThemeId = themes[0]!.id

export function getThemeById(id: string): ThemeDefinition {
  const resolved = LEGACY_THEME_IDS[id] ?? id
  return themes.find((t) => t.id === resolved) ?? themes[0]!
}
